Fix old-style function declarations
In ruby/ruby@5ff47e0c8a97940a6f77f961ab43ebea87256dfa, compile flag
`-Werror=old-style-definition` was added which requires `void` in
functions which accept no arguments.

Otherwise, compilation fails like this:

```
error: old-style function definition [-Werror=old-style-definition]
   12 | static inline c_buffer_t c_buffer_init()
      |                          ^~~~~~~~~~~~~
```